language: bash
before_install:
- sudo apt-get update
- sudo apt-get install -y -qq
           build-essential
           latex-make
           texlive-base
           texlive-xetex
           texlive-latex-recommended
           texlive-latex-extra
           texlive-extra-utils
           texlive-fonts-recommended
           texlive-font-utils
           texlive-lang-french
           texlive-math-extra
           texlive-pictures
           latex-xcolor
           texlive-bibtex-extra
           pgf
           lmodern
           biber
           latexmk
           ghostscript

install: true
script:
  - make

deploy:
  local-dir: build
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
env:
  global:
    secure: "mxtSbCt5/y5//SEPkcRiwFqEg07xHYj6fL2BgMGqoY+ZtSXvbWKIn2jdAa3kK8T/IxLLy2PJybig9oz+RMTdBftEG9j4nGUqzzb+Guw+LgKo+e3mGF2gZrtgZajOm5gxlaJpaQdXpxEtTG7Q+OmYZVmMzk5oiy71EJ0CzZ3M4M1/LmsgLFnysPgX4Zi2zZlHdn58lo6gcIg8U5VuQUIiqTdU8rTP5BkD4uAjR8moxZQ8E2KY5zSRDtsIKJJftNFcGOwz5OWHy/ifNtcDvG6AptJIHSV0R4ltyearj66Y9Cl3lrmeKgBqn9rehxKd0Io1LZrthoMk+aZWQdx2n/DdWH0+ZBj2u8XqybdnpK3+OrY5Rx12KRmW1i/2ASwPu1qrdncSNhJp7Q7NIvFqmZJ0Q2+a0nyyKPdYWKQawubGdVVBye2vf4JBHZibCL/k3FoXZh3MFnsoL2VCCzr3JtPRZY65aPQdUX5wxQXYwWO4yEhtefivrpNmkxw2HMmUqjPRc2YajRbzO/CSpqSRh36Y6bN4Opjk9daSZbxQHOda+jarKfy1/ER1ZrVasgDls9geK8RohT4jFjVtke3/xh+T1rY8FXMb+ja7Ar0NPyQUkWekXZGrCaGeckbqjO9/rsO6gSVFMOpYbfbZCBuWSjef+YTnjLO0uglLlJipfgvBcrs="
